name: Build PolyReg EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # PyInstaller works best with 3.10/3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy pandas scikit-learn matplotlib scipy PyQt6

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed PolyReg.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PolyReg-exe
          path: dist/PolyReg.exe
